# Generated by Django 6.0.2 on 2026-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('budget', models.PositiveIntegerField()),
            ],
        ),
    ]
