# Generated by Django 6.0.2 on 2026-03-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
