# Generated by Django 6.0.2 on 2026-03-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('acc_num', models.BigAutoField(default=1234567890, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('phone', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('nomine_name', models.CharField(max_length=40)),
                ('balance', models.FloatField(default=1000)),
                ('pin', models.CharField(default='0000', max_length=64)),
                ('images', models.ImageField(upload_to='profiles')),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acc_type')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.relationship')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
