# Generated by Django 6.0.2 on 2026-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acc_num',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
