# Generated by Django 6.0.2 on 2026-03-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='image',
            field=models.ImageField(default=0, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
