# Generated by Django 6.0.2 on 2026-03-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_db_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_db',
            old_name='phone',
            new_name='mobile',
        ),
    ]
