# Generated by Django 6.0.2 on 2026-03-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('sub', models.CharField(max_length=100)),
            ],
        ),
    ]
