# Generated by Django 6.0.2 on 2026-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_db',
            name='battery',
            field=models.CharField(default='5000mAh', max_length=100),
        ),
        migrations.AddField(
            model_name='brand_db',
            name='camera',
            field=models.CharField(default='12MP', max_length=100),
        ),
        migrations.AddField(
            model_name='brand_db',
            name='display',
            field=models.CharField(default='6.1 AMOLED', max_length=100),
        ),
        migrations.AddField(
            model_name='brand_db',
            name='processor',
            field=models.CharField(default='Snapdragon', max_length=100),
        ),
        migrations.AddField(
            model_name='brand_db',
            name='warranty',
            field=models.CharField(default='1 Year', max_length=100),
        ),
    ]
