# Generated by Django 6.0.2 on 2026-03-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_db_battery_brand_db_camera_brand_db_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand_db',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='brand_db',
            name='display',
        ),
        migrations.RemoveField(
            model_name='brand_db',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='brand_db',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='brand_db',
            name='rom',
        ),
        migrations.RemoveField(
            model_name='brand_db',
            name='warranty',
        ),
    ]
