# Generated by Django 6.0.2 on 2026-03-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_brand_db_camera_remove_brand_db_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('battery', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Brand_db',
        ),
    ]
