# Generated by Django 6.0.2 on 2026-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='description',
            field=models.TextField(default='Java Developer'),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='doj',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='phone',
            field=models.BigIntegerField(default=9876543210),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='sal',
            field=models.IntegerField(default=10000),
        ),
    ]
